### ISSUE TITLE
Version 1.24.3 - Getting "A JavaScript error occurred in the main process" when launching app

### ISSUE THREAD

**Issue by timmay7** [bitwarden/desktop#685]
After updating to 1.24.3, launching the app results in an error message that says:

A JavaScript error occurred in the main process
Error: Cannot find module 'browser-hrtime'

My only option is to click OK. The app does not open at all.

**Comment by m-p-3** [comment]
Same issue, trying to reinstall the app through the install on the website (`Bitwarden-Installer-1.24.3.exe`) gives the following error:
![Screenshot 2021-01-25 193325](https://user-images.githubusercontent.com/3731432/105783345-3c5bdc00-5f44-11eb-8bb9-a38a4190bebd.png)

**Comment by giovannyreyeso** [comment]
Same issue. !  on Mac

**Comment by kspearrin** [comment]
Please reinstall v1.24.4. The download link on our website is updated. Sorry for the problem.
